---

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true

- name: Enable PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started
