name: Ansible CD Deploy

on:
  workflow_run:
    workflows: ["Terraform VM Resource Apply"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Ansible Continuous Deployment
    # CHỈ CHẠY khi workflow cha hoàn thành VÀ kết quả là 'success'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    environment: tailscale-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailscale Mesh Network via OIDC
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CI_CLIENT_ID }}
          audience: ${{ secrets.TAILSCALE_CI_AUDIENCE }}
          tags: tag:ci

      - name: Trigger Remote Ansible Execution on CM Node via Tailscale SSH
        run: |
          ssh -o StrictHostKeyChecking=no azureadmin@vm-cm-01 "cd /home/azureadmin/hybrid-infrastructure-lab && git pull origin main && cd ansible && ./run.sh"